DROP DATABASE IF EXISTS WebStorage;

CREATE DATABASE WebStorage
    CHARACTER SET utf8
    COLLATE utf8_general_ci;

USE WebStorage;

DROP TABLE IF EXISTS User;
CREATE TABLE User (
    ID INT NOT NULL,
    NAME varchar(120) NOT NULL,
    USER_NAME varchar(120) NOT NULL,
    EMAIL varchar(120) NOT NULL,
    REGISTRATION datetime NOT NULL,
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS Domain;
CREATE TABLE Domain(
    ID INT NOT NULL,
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS Store;
CREATE TABLE Store(
    ID INT NOT NULL,
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS DataStore;
CREATE TABLE DataStore(
    ID INT NOT NULL,
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS Bill;
CREATE TABLE Bill(
    ID INT NOT NULL,
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS Payment;
CREATE TABLE Payment(
    ID INT NOT NULL,
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS Statistic;
CREATE TABLE Statistic(
    ID INT NOT NULL,
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS Notification;
CREATE TABLE Notification(
    ID INT NOT NULL,
    PRIMARY KEY (ID)
);