version: "3.1"

services:
  db:
    image: mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=WebStorage
    volumes:
      - ./:/scripts
    command: "./scripts/startup.sh"

  adminer:
    image: adminer
    restart: unless-stopped
    environment:
      - ADMINER_DEFAULT_SERVER=db
    ports:
      - 9999:8080
